---
server:
  port: 8080
app:
  version: "0.0.1"
spring:
  mvc:
    view:
      prefix: "/WEB-INF/jsp/"
      suffix: ".jsp"
    locale-resolver:
  datasource:
    url: jdbc:postgresql://localhost:5432/conference_app
    username: postgres
    password: Welcome
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
